version: '3.7'

services:
  postgresql_db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - diary-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      


volumes:
  diary-data:
